export interface Track {
  id: string;
  title: string;
  duration: string;
  fileUrl: string;
}

export interface AlbumTracks {
  [albumId: string]: Track[];
}

export const albumTracks: AlbumTracks = {
  "1": [
    { id: "1-1", title: "3x", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - 3x (SPOTISAVER).mp3" },
    { id: "1-2", title: "All Star", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - All Star (SPOTISAVER).mp3" },
    { id: "1-3", title: "Baghdad", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Baghdad (SPOTISAVER).mp3" },
    { id: "1-4", title: "Blonde", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Blonde (SPOTISAVER).mp3" },
    { id: "1-5", title: "Boss Up", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Boss Up (SPOTISAVER).mp3" },
    { id: "1-6", title: "Congrats", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Congrats (SPOTISAVER).mp3" },
    { id: "1-7", title: "For Da Flex", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - For Da Flex (SPOTISAVER).mp3" },
    { id: "1-8", title: "Kills", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Kills (SPOTISAVER).mp3" },
    { id: "1-9", title: "Kome Thru", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Kome Thru (SPOTISAVER).mp3" },
    { id: "1-10", title: "Me When", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Me When (SPOTISAVER).mp3" },
    { id: "1-11", title: "Nothing", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Nothing (SPOTISAVER).mp3" },
    { id: "1-12", title: "Pop", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Pop (SPOTISAVER).mp3" },
    { id: "1-13", title: "Str8 Flexin", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Str8 Flexin (SPOTISAVER).mp3" },
    { id: "1-14", title: "Talking 2 A Ghost", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Talking 2 A Ghost (SPOTISAVER).mp3" },
    { id: "1-15", title: "Trenches", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Trenches (SPOTISAVER).mp3" },
    { id: "1-16", title: "Uno", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Uno (SPOTISAVER).mp3" },
    { id: "1-17", title: "Worst Part", duration: "3:00", fileUrl: "/downloads/osamason/flex-musix/OsamaSon - Worst Part (SPOTISAVER).mp3" },
  ],
  "2": [
    { id: "2-1", title: "Addicted", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Addicted (SPOTISAVER).mp3" },
    { id: "2-2", title: "Function", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Function (SPOTISAVER).mp3" },
    { id: "2-3", title: "Get Away", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Get Away (SPOTISAVER).mp3" },
    { id: "2-4", title: "Gintama", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Gintama (SPOTISAVER).mp3" },
    { id: "2-5", title: "Guap Man", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Guap Man (SPOTISAVER).mp3" },
    { id: "2-6", title: "Habits", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Habits (SPOTISAVER).mp3" },
    { id: "2-7", title: "In It", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - In It (SPOTISAVER).mp3" },
    { id: "2-8", title: "Inferno", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Inferno (SPOTISAVER).mp3" },
    { id: "2-9", title: "Its A Party", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Its A Party (SPOTISAVER).mp3" },
    { id: "2-10", title: "Maag Dump", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Maag Dump (SPOTISAVER).mp3" },
    { id: "2-11", title: "She woke Up", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - She woke Up (SPOTISAVER).mp3" },
    { id: "2-12", title: "T193", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - T193 (SPOTISAVER).mp3" },
    { id: "2-13", title: "Victory Lap", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Victory Lap (SPOTISAVER).mp3" },
    { id: "2-14", title: "Whats Happening", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Whats Happening (SPOTISAVER).mp3" },
    { id: "2-15", title: "Worldwide", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - Worldwide (SPOTISAVER).mp3" },
    { id: "2-16", title: "yea i kno", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon - yea i kno (SPOTISAVER).mp3" },
    { id: "2-17", title: "OsamaSon, Che - FMJ (feat.Che)(SPOTISAVER)", duration: "3:00", fileUrl: "/downloads/osamason/psykotic/OsamaSon, Che - FMJ (feat.Che)(SPOTISAVER).mp3" },
  ],
  "3": [
    { id: "3-1", title: "Anti", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Anti (SPOTISAVER).mp3" },
    { id: "3-2", title: "Dont Let Looks Fool", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Dont Let Looks Fool (SPOTISAVER).mp3" },
    { id: "3-3", title: "Kutta", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Kutta (SPOTISAVER).mp3" },
    { id: "3-4", title: "Lambtruck", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Lambtruck (SPOTISAVER).mp3" },
    { id: "3-5", title: "Leh Go", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Leh Go (SPOTISAVER).mp3" },
    { id: "3-6", title: "Lil O", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Lil O (SPOTISAVER).mp3" },
    { id: "3-7", title: "Pipeup", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Pipeup (SPOTISAVER).mp3" },
    { id: "3-8", title: "Summer Sixteen", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Summer Sixteen (SPOTISAVER).mp3" },
    { id: "3-9", title: "Troops", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Troops (SPOTISAVER).mp3" },
    { id: "3-10", title: "Vlone", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Vlone (SPOTISAVER).mp3" },
    { id: "3-11", title: "Werkin", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - Werkin (SPOTISAVER).mp3" },
    { id: "3-12", title: "X & Sex", duration: "3:00", fileUrl: "/downloads/osamason/osama-season/OsamaSon - X & Sex (SPOTISAVER).mp3" },
  ],
  "4": [
    { id: "4-1", title: "chronic", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/chronic_spotdown.org.mp3" },
    { id: "4-2", title: "desprazer", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/desprazer_spotdown.org.mp3" },
    { id: "4-3", title: "it's not what i have", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/it's not what i have_spotdown.org.mp3" },
    { id: "4-4", title: "laps", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/laps_spotdown.org.mp3" },
    { id: "4-5", title: "line sayer", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/line sayer_spotdown.org.mp3" },
    { id: "4-6", title: "ok like", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/ok like_spotdown.org.mp3" },
    { id: "4-7", title: "picture frames", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/picture frames_spotdown.org.mp3" },
    { id: "4-8", title: "poster", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/poster_spotdown.org.mp3" },
    { id: "4-9", title: "rude", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/rude_spotdown.org.mp3" },
    { id: "4-10", title: "run outro", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/run outro_spotdown.org.mp3" },
    { id: "4-11", title: "swear to god", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/swear to god_spotdown.org.mp3" },
    { id: "4-12", title: "war", duration: "3:00", fileUrl: "/downloads/twikipedia/chronic/war_spotdown.org.mp3" },
  ],
  "5": [
    { id: "5-1", title: "anyone but you", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/anyone but you_spotdown.org.mp3" },
    { id: "5-2", title: "boy", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/boy_spotdown.org.mp3" },
    { id: "5-3", title: "cardboard boxes", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/cardboard boxes_spotdown.org.mp3" },
    { id: "5-4", title: "dry your eyes", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/dry your eyes_spotdown.org.mp3" },
    { id: "5-5", title: "far apart", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/far apart_spotdown.org.mp3" },
    { id: "5-6", title: "figure me out", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/figure me out_spotdown.org.mp3" },
    { id: "5-7", title: "final feliz", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/final feliz_spotdown.org.mp3" },
    { id: "5-8", title: "garden", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/garden_spotdown.org.mp3" },
    { id: "5-9", title: "learn yourself", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/learn yourself_spotdown.org.mp3" },
    { id: "5-10", title: "paper planes", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/paper planes_spotdown.org.mp3" },
    { id: "5-11", title: "room for one", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/room for one_spotdown.org.mp3" },
    { id: "5-12", title: "seams", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/seams_spotdown.org.mp3" },
    { id: "5-13", title: "windchimes", duration: "3:00", fileUrl: "/downloads/twikipedia/for-the-rest-of-your-life/windchimes_spotdown.org.mp3" },
  ],
  "6": [
    { id: "6-1", title: "hurt", duration: "3:00", fileUrl: "/downloads/twikipedia/still-life/hurt_spotdown.org.mp3" },
    { id: "6-2", title: "i wanna be the guy", duration: "3:00", fileUrl: "/downloads/twikipedia/still-life/i wanna be the guy_spotdown.org.mp3" },
    { id: "6-3", title: "killing time", duration: "3:00", fileUrl: "/downloads/twikipedia/still-life/killing time_spotdown.org.mp3" },
    { id: "6-4", title: "sail", duration: "3:00", fileUrl: "/downloads/twikipedia/still-life/sail_spotdown.org.mp3" },
    { id: "6-5", title: "understand", duration: "3:00", fileUrl: "/downloads/twikipedia/still-life/understand_spotdown.org.mp3" },
  ],
  "7": [
    { id: "7-1", title: "carpe diem avem", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/carpe diem avem_spotdown.org.mp3" },
    { id: "7-2", title: "conjoined (interlude)", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/conjoined (interlude)_spotdown.org.mp3" },
    { id: "7-3", title: "half enough", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/half enough_spotdown.org.mp3" },
    { id: "7-4", title: "hourglass memory", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/hourglass memory_spotdown.org.mp3" },
    { id: "7-5", title: "medicine", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/medicine_spotdown.org.mp3" },
    { id: "7-6", title: "mundo", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/mundo_spotdown.org.mp3" },
    { id: "7-7", title: "nothing for a moment", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/nothing for a moment_spotdown.org.mp3" },
    { id: "7-8", title: "only human _ anywhere at all", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/only human _ anywhere at all_spotdown.org.mp3" },
    { id: "7-9", title: "promise", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/promise_spotdown.org.mp3" },
    { id: "7-10", title: "rifle", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/rifle_spotdown.org.mp3" },
    { id: "7-11", title: "snowman, snowman", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/snowman, snowman_spotdown.org.mp3" },
    { id: "7-12", title: "symptom", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/symptom_spotdown.org.mp3" },
    { id: "7-13", title: "tackle", duration: "3:00", fileUrl: "/downloads/keyvslocket/i-felt-like-a-sketch/tackle_spotdown.org.mp3" },
  ],
  "8": [
    { id: "8-1", title: "coincidência", duration: "3:00", fileUrl: "/downloads/keyvslocket/coincidencia/coincidência_spotdown.org.mp3" },
    { id: "8-2", title: "don't be so full of yourself", duration: "3:00", fileUrl: "/downloads/keyvslocket/coincidencia/don't be so full of yourself_spotdown.org.mp3" },
  ],
  "9": [
    { id: "9-1", title: "running", duration: "3:00", fileUrl: "/downloads/keyvslocket/my-demos/running_spotdown.org.mp3" },
    { id: "9-2", title: "safeword", duration: "3:00", fileUrl: "/downloads/keyvslocket/my-demos/safeword_spotdown.org.mp3" },
    { id: "9-3", title: "wanted", duration: "3:00", fileUrl: "/downloads/keyvslocket/my-demos/wanted_spotdown.org.mp3" },
  ],
  "10": [
    { id: "10-1", title: "antonym", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/antonym_spotdown.org.mp3" },
    { id: "10-2", title: "cupid", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/cupid_spotdown.org.mp3" },
    { id: "10-3", title: "dionaea", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/dionaea_spotdown.org.mp3" },
    { id: "10-4", title: "jane the killer", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/jane the killer_spotdown.org.mp3" },
    { id: "10-5", title: "listerine", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/listerine_spotdown.org.mp3" },
    { id: "10-6", title: "nyras", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/nyras_spotdown.org.mp3" },
    { id: "10-7", title: "uncool", duration: "3:00", fileUrl: "/downloads/bunii/8-30-is-too-early/uncool_spotdown.org.mp3" },
  ],
  "11": [
    { id: "11-1", title: "GOOD RIDDANCE", duration: "3:00", fileUrl: "/downloads/bunii/six/GOOD RIDDANCE_spotdown.org.mp3" },
    { id: "11-2", title: "MINE", duration: "3:00", fileUrl: "/downloads/bunii/six/MINE_spotdown.org.mp3" },
    { id: "11-3", title: "NEED IT", duration: "3:00", fileUrl: "/downloads/bunii/six/NEED IT_spotdown.org.mp3" },
    { id: "11-4", title: "REGRET", duration: "3:00", fileUrl: "/downloads/bunii/six/REGRET_spotdown.org.mp3" },
    { id: "11-5", title: "SAINT", duration: "3:00", fileUrl: "/downloads/bunii/six/SAINT_spotdown.org.mp3" },
  ],
  "12": [
    { id: "12-1", title: "deaf", duration: "3:00", fileUrl: "/downloads/bunii/bastard/deaf_spotdown.org.mp3" },
    { id: "12-2", title: "eatmydust (feat. ankle)", duration: "3:00", fileUrl: "/downloads/bunii/bastard/eatmydust (feat. ankle)_spotdown.org.mp3" },
    { id: "12-3", title: "et", duration: "3:00", fileUrl: "/downloads/bunii/bastard/et_spotdown.org.mp3" },
    { id: "12-4", title: "flowerbed", duration: "3:00", fileUrl: "/downloads/bunii/bastard/flowerbed_spotdown.org.mp3" },
    { id: "12-5", title: "gown", duration: "3:00", fileUrl: "/downloads/bunii/bastard/gown_spotdown.org.mp3" },
    { id: "12-6", title: "selah", duration: "3:00", fileUrl: "/downloads/bunii/bastard/selah_spotdown.org.mp3" },
    { id: "12-7", title: "so good", duration: "3:00", fileUrl: "/downloads/bunii/bastard/so good_spotdown.org.mp3" },
    { id: "12-8", title: "theirthoughts", duration: "3:00", fileUrl: "/downloads/bunii/bastard/theirthoughts_spotdown.org.mp3" },
    { id: "12-9", title: "toothache", duration: "3:00", fileUrl: "/downloads/bunii/bastard/toothache_spotdown.org.mp3" },
    { id: "12-10", title: "watermolen", duration: "3:00", fileUrl: "/downloads/bunii/bastard/watermolen_spotdown.org.mp3" },
    { id: "12-11", title: "yes", duration: "3:00", fileUrl: "/downloads/bunii/bastard/yes_spotdown.org.mp3" },
  ],
  "13": [
    { id: "13-1", title: "<3", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/<3_spotdown.org.mp3" },
    { id: "13-2", title: "anemic", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/anemic_spotdown.org.mp3" },
    { id: "13-3", title: "damage", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/damage_spotdown.org.mp3" },
    { id: "13-4", title: "dead girl", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/dead girl_spotdown.org.mp3" },
    { id: "13-5", title: "draculea", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/draculea_spotdown.org.mp3" },
    { id: "13-6", title: "fallen", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/fallen_spotdown.org.mp3" },
    { id: "13-7", title: "horror", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/horror_spotdown.org.mp3" },
    { id: "13-8", title: "kesha k", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/kesha k_spotdown.org.mp3" },
    { id: "13-9", title: "laylow", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/laylow_spotdown.org.mp3" },
    { id: "13-10", title: "let me b", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/let me b_spotdown.org.mp3" },
    { id: "13-11", title: "misery", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/misery_spotdown.org.mp3" },
    { id: "13-12", title: "numb", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/numb_spotdown.org.mp3" },
    { id: "13-13", title: "rose", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/rose_spotdown.org.mp3" },
    { id: "13-14", title: "spaz", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/spaz_spotdown.org.mp3" },
    { id: "13-15", title: "undercover", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/undercover_spotdown.org.mp3" },
    { id: "13-16", title: "valentine", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/valentine_spotdown.org.mp3" },
    { id: "13-17", title: "witchybitchy", duration: "3:00", fileUrl: "/downloads/jaydes/ghetto-cupid/witchybitchy_spotdown.org.mp3" },
  ],
  "14": [
    { id: "14-1", title: "4u", duration: "3:00", fileUrl: "/downloads/jaydes/romanticism/4u_spotdown.org.mp3" },
    { id: "14-2", title: "convenience", duration: "3:00", fileUrl: "/downloads/jaydes/romanticism/convenience_spotdown.org.mp3" },
    { id: "14-3", title: "migraine", duration: "3:00", fileUrl: "/downloads/jaydes/romanticism/migraine_spotdown.org.mp3" },
    { id: "14-4", title: "tylenol", duration: "3:00", fileUrl: "/downloads/jaydes/romanticism/tylenol_spotdown.org.mp3" },
  ],
  "15": [
    { id: "15-1", title: "I plan to leave the internet fuck your trend", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/I plan to leave the internet fuck your trend_spotdown.org.mp3" },
    { id: "15-2", title: "hysteric", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/hysteric_spotdown.org.mp3" },
    { id: "15-3", title: "i hate people", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/i hate people_spotdown.org.mp3" },
    { id: "15-4", title: "junkie", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/junkie_spotdown.org.mp3" },
    { id: "15-5", title: "let it burn", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/let it burn_spotdown.org.mp3" },
    { id: "15-6", title: "miss america", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/miss america_spotdown.org.mp3" },
    { id: "15-7", title: "repent!!!", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/repent!!!_spotdown.org.mp3" },
    { id: "15-8", title: "scary movie", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/scary movie_spotdown.org.mp3" },
    { id: "15-9", title: "the more you know", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/the more you know_spotdown.org.mp3" },
    { id: "15-10", title: "wanna take advantage of you", duration: "3:00", fileUrl: "/downloads/jaydes/count-up-dracula/wanna take advantage of you_spotdown.org.mp3" },
  ],
};
